/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {
  interface HTMLMadnessCastElement extends HTMLStencilElement {
    'episode': string;
  }
  var HTMLMadnessCastElement: {
    prototype: HTMLMadnessCastElement;
    new (): HTMLMadnessCastElement;
  };
  interface HTMLElementTagNameMap {
    'madness-cast': HTMLMadnessCastElement;
  }
  interface ElementTagNameMap {
    'madness-cast': HTMLMadnessCastElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'madness-cast': JSXElements.MadnessCastAttributes;
    }
  }
  namespace JSXElements {
    export interface MadnessCastAttributes extends HTMLAttributes {
      'episode'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
